name: Codeception Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, openssl, json
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Codeception tests
        run: vendor/bin/codecept run unit
