name: Publish to Packagist

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Packagist
        run: |
          curl -X POST https://packagist.org/api/update-package \
            -u "${{ secrets.PACKAGIST_USERNAME }}:${{ secrets.PACKAGIST_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"repository":"https://github.com/mervick/aes-bridge-php"}'
