name: Update Packagist Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: packagist
      url: https://packagist.org/packages/mervick/aes-bridge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Send Packagist Update Request
      run: |
        curl -XPOST -H'content-type:application/json' \
          "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
          -d'{"repository":{"url":"https://github.com/mervick/aes-bridge-php"}}'
